import { NavInfoProps } from "../types";

export const navigationEntranceList:NavInfoProps[] = [
  {
    title: "react篇",
    description: "react学习沉淀",
    list: [
      {
        title: "react理论",
        tips: "react理论总结",
        path: "",
        pathType: "",
        statusCode: "NEW",
        statusText: "NEW",
      },
      {
        title: "react哲学",
        tips: "react哲学总结",
        path: "",
        pathType: "",
        statusCode: "NEW",
        statusText: "NEW",
      },
      {
        title: "reactAPI实践",
        tips: "react项目实践沉淀",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "react组件实战",
        tips: "react项目组件沉淀",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "react状态管理",
        tips: "react状态管理沉淀",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "react原理",
        tips: "react原理深入学习沉淀",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
    ],
  },
  {
    title: "git篇",
    description: "git学习沉淀",
    list: [
      {
        title: "git基本概念",
        tips: "git配置信息，Git 工作区、暂存区和版本库概念",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "git操作篇",
        tips: "git常用操作总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "git其他操作篇",
        tips: "git非常用操作沉淀",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
    ],
  },
  {
    title: "数据结构",
    description: "javaScipt数据结构",
    list: [
      {
        title: "栈",
        tips: "实现栈",
        path: "",
        pathType: "outer",
        statusCode: "",
        statusText: "",
      },
      {
        title: "队列",
        tips: "实现队列，优先队列，循环队列",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "集合",
        tips: "创建集合、并集、交集、差集、子集",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "链表",
        tips: "创建链表、双向链表",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "字典",
        tips: "实现字典",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "树",
        tips: "实现树",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "图",
        tips: "实现图",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "堆",
        tips: "实现堆",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
    ],
  },
  {
    title: "算法",
    description: "javaScipt算法",
    list: [
      {
        title: "算法设计思想",
        tips: "算法设计思想总结",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "冒泡算法",
        tips: "冒泡算法原理及实现",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "选择算法",
        tips: "选择算法原理及实现",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "插入算法",
        tips: "插入算法原理及实现",
        path: "",
        pathType: "",
        statusCode: "",
        statusText: "",
      },
      {
        title: "归并算法",
        tips: "归并算法原理及实现",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "快速算法",
        tips: "快速算法原理及实现",
        path: "",
        pathType: "",
        statusCode: "NEW",
        statusText: "NEW",
      },
      {
        title: "顺序算法",
        tips: "顺序算法原理及实现",
        path: "",
        pathType: "",
        statusCode: "NEW",
        statusText: "NEW",
      },
      {
        title: "二分搜索",
        tips: "顺序算法原理及实现",
        path: "",
        pathType: "",
        statusCode: "NEW",
        statusText: "NEW",
      },
    ],
  },
  {
    title: "webpack",
    description: "webpack概念及原理学习总结",
    list: [
      {
        title: "webpack基本概念",
        tips: "webpack基本概念总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "webpack 核心概念",
        tips: "webpack 核心概念总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "webpack 构建流程",
        tips: "webpack 构建流程学习总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
    ],
  },
  {
    title: "浏览器篇",
    description: "浏览器相关知识点总结",
    list: [
      {
        title: "浏览器安全",
        tips: "",
        path: "",
        pathType: "",
        statusCode: "HOT",
        statusText: "HOT",
      },
      {
        title: "进程和线程",
        tips: "进程和线程学习沉淀",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "浏览器缓存",
        tips: "浏览器缓存概念及原理学习总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "浏览器组成",
        tips: "浏览器组成学习总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "浏览器渲染原理",
        tips: "浏览器渲染原理学习总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "浏览器本地存储",
        tips: "浏览器本地存储学习总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "同源策略原理",
        tips: "同源策略原理学习总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "浏览器事件机制",
        tips: "浏览器事件机制学习总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "垃圾回收机制",
        tips: "浏览器垃圾回收机制学习总结",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
    ],
  },
  {
    title: "计算机网络",
    description: "计算机网络知识点总结",
    list: [
      {
        title: "Nginx",
        tips: "",
        path: "",
        pathType: "",
        statusCode: "NEW",
        statusText: "NEW",
      },
      {
        title: "跨域",
        tips: "",
        path: "",
        pathType: "",
        statusCode: "WAIT_ONLINE",
        statusText: "敬请期待",
      },
      {
        title: "axios",
        tips: "",
        path: "/",
        pathType: "",
        statusCode: "NEW",
        statusText: "NEW",
      },
      {
        title: "http请求",
        tips: "",
        path: "/",
        pathType: "",
        statusCode: "NEW",
        statusText: "NEW",
      },
      {
        title: "DNS",
        tips: "",
        path: "/",
        pathType: "",
        statusCode: "NEW",
        statusText: "NEW",
      },
    ],
  },
  {
    title: "前端工程化",
    description: "前端工程化概念及原理学习总结",
    list:[
        {
            title: "前端模块化",
            tips: "",
            path: "/",
            pathType: "",
            statusCode: "NEW",
            statusText: "NEW",
        },
        {
            title: "前端组件化",
            tips: "",
            path: "/",
            pathType: "",
            statusCode: "NEW",
            statusText: "NEW",
        },
        {
            title: "css module",
            tips: "",
            path: "/",
            pathType: "",
            statusCode: "NEW",
            statusText: "NEW",
        },
    ]
  },
  {
    title: "性能优化",
    description: "性能优化总结沉淀",
    list:[
        {
            title: "渲染优化",
            tips: "",
            path: "/",
            pathType: "",
            statusCode: "NEW",
            statusText: "NEW",
        },
        {
            title: "requestAnimationFrame",
            tips: "",
            path: "/",
            pathType: "",
            statusCode: "NEW",
            statusText: "NEW",
        }
    ]
  },
//   {
//     title: "javaScript",
//     description: "javaScript基础篇",
//     list:[
//         {
//             title: "javaScript创建对象",
//             tips: "",
//             path: "/",
//             pathType: "",
//             statusCode: "NEW",
//             statusText: "NEW",
//         },
//         {
//             title: "javaScript原型、原型链和继承",
//             tips: "",
//             path: "/",
//             pathType: "",
//             statusCode: "NEW",
//             statusText: "NEW",
//         },
//         {
//             title: "javaScript 作用域，作用域链及闭包",
//             tips: "",
//             path: "/",
//             pathType: "",
//             statusCode: "NEW",
//             statusText: "NEW",
//         }
//     ]
//   }
];
